### ISSUE TITLE
display amount of second doses

### ISSUE THREAD

**Issue by MergHQ** [MergHQ/piikki#2]

**Comment by lucasrodes** [comment]
Interested in this feature for project https://github.com/sociepy/covid19-vaccination-subnational/

**Comment by MergHQ** [comment]
Hello,

Good to hear. I'll see if I can find some time to implement this feature. After that the data will be available from the api.

**Comment by MergHQ** [comment]
There's now data of the second dose in https://piikki-api.lab.juiciness.io/administrations/ https://piikki-api.lab.juiciness.io/administrations/summary https://piikki-api.lab.juiciness.io/administrations/ageGroups

Keep in mind that the `areaId` is not related to data from the official source (thl.fi), so don't include it.

If there's anything you need or you notice any issues with the data, please open a issue for this repository.

**Comment by lucasrodes** [comment]
This is really helpful and really fast! Thanks for your response. 

I'll be integrating Finland this weekend. I Will let you know how it goes.

**Comment by MergHQ** [comment]
No problem, thank you!

Also, don't include the `id` field in the ageGroup data since it's also something that's not coming from official sources.
